apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

# Staging: 1 replica is enough.
replicas:
  - name: aws-trivia
    count: 1

# Staging image tag — bumped manually from dev (PR-based promotion).
images:
  - name: aws-trivia
    newName: 748415433090.dkr.ecr.us-east-1.amazonaws.com/aws-trivia
    newTag: bb28b9528d0a8100ef88dce6d102ffdb9c9ccea8

patches:
  - target:
      kind: Ingress
      name: aws-trivia
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: trivia-staging.lab.yurykuvaev.com
