name: proxy-payments
replicas: 3
ingress:
  enabled: true
  host: proxy-payments.lab.yurykuvaev.com
  albGroup: lab-dev
env:
  - name: WHOAMI_NAME
    value: proxy-payments-prod
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 256Mi }
