apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

replicas:
  - name: whoami
    count: 1

patches:
  - target:
      kind: Ingress
      name: whoami
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: whoami-dev.lab.yurykuvaev.com
