name: proxy-checkout
replicas: 3
ingress:
  enabled: true
  host: proxy-checkout.lab.yurykuvaev.com
  albGroup: lab-dev
env:
  - name: WHOAMI_NAME
    value: proxy-checkout-prod
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits:   { cpu: 500m, memory: 256Mi }
