apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

# Dev: single replica.
replicas:
- count: 1
  name: aws-trivia

# CI auto-bumps this tag on every successful build of aws-trivia-game.
# Promotion to staging/prod is manual (PR moving this newTag value into
# the corresponding overlay).
images:
- name: aws-trivia
  newName: 748415433090.dkr.ecr.us-east-1.amazonaws.com/aws-trivia
  newTag: fe173bab86ed97f8ccfcaa63fb6f405a32d5ecc0

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: trivia-dev.lab.yurykuvaev.com
  target:
    kind: Ingress
    name: aws-trivia
