apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yurykuvaev/k8s-gitops-apps
    targetRevision: main
    path: apps/whoami/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
