apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- configmap.yaml

images:
- name: aws-trivia
  newName: 748415433090.dkr.ecr.us-east-1.amazonaws.com/aws-trivia
  newTag: bb28b9528d0a8100ef88dce6d102ffdb9c9ccea8
