apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxy-service.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "proxy-service.name" . }}
    app.kubernetes.io/managed-by: argocd
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxy-service.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "proxy-service.name" . }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthcheckPath }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.healthcheckPath }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
